project:
  output-dir: _output
date: today
author:
  - name: 林協霆
    affiliation: KFSYSCC
    role: "Conceived and designed the study"
from: markdown+emoji
format:
  revealjs:
    theme: assets/style.scss
    auto-stretch: true
    number-depth: 1
    number-sections: true
    height: 900
    width: 1600
    margin: 0.15
    slide-number: true
    default-timing: 60
    code-line-numbers: true
    # code-overflow: scroll
    highlight-style: github
    code-copy: hover
    # logo: https://i.imgur.com/W8Z8w22.png
    progress: true
    mouse-wheel: false
    section-divs: true
    header-includes: |
      <script src="assets/custom.js" type="application/javascript"></script>
    controls: false
    title-slide-attributes:
      data-state: "hide-menubar"
    menu: true
    simplemenu:
      barhtml:
        header: "<div class='menubar'><ul class='menu'></ul><div>"
      scale: 0.3
filters:
  - reveal-auto-agenda
  - timer
  - code-fullscreen
  - roughnotation
  - diagram
auto-agenda:
  bullets: numbered
  heading: "Now we are going to talk about:"
countdown:
  font_size: "10rem"
  color_background: "white"
revealjs-plugins:
  # - spotlight
  # - confetti
  - quiz
  - simplemenu
  - codefocus
  - webcam
execute:
  enabled: false
  echo: true
